### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by hasnainali659** [deeplearning-wisc/stud#10]
How can we modify the code base for our custom dataset?

**Comment by d12306** [comment]
hi, @hasnainali659 , thanks for the interest in our work! for custom datasets, you should convert it into the video-based coco format, as we did in this file. https://github.com/deeplearning-wisc/stud/blob/main/datasets/bdd100k2coco.py

**Comment by hasnainali659** [comment]
Thanks for the response. After this step for training do we have to modify srce/builtin.py file also?

**Comment by d12306** [comment]
@hasnainali659 , yes! you can then register the dataset for training and inference.
