### ISSUE TITLE
Where is the nobackup/dataset/my_xfdu folder?

### ISSUE THREAD

**Issue by qq470255867** [deeplearning-wisc/stud#11]
it's a awesome project but I just can't found the folders in the [https://github.com/deeplearning-wisc/stud/blob/main/src/data/builtin.py](url) #45,which make me can't run the train process.please resolve my confusion.

**Comment by d12306** [comment]
hi, @qq470255867 , the folder is just for you to place your training data. You can feel free to replace it with your own file name.
