### ISSUE TITLE
Question about run my own test and visualization

### ISSUE THREAD

**Issue by BigBuffa1o** [deeplearning-wisc/stud#13]
Thanks for this amazing work.

i want to use this code and a pre-train model that you provoide to just run on a signle test img to get a visual result,but i find this diffcult as iam not much famlilar with detrecton2,i try to use the code in issue 4 without modify the code/yaml but just the path,i only get this kind of the img with no class name.

i think its the problem of yaml file as i havent modified it and also the dataset in yaml file i literally didn't download it too,but as iam only want to test on a single img of my own and visualize it that's all,do i have to download the whole dataset?i dont need train just use pre-trained STUD model to test on one img to get a successful result contain OOD.

Any guide would be appraciate,thanks again!
![f939e073-9189-496f-a796-5523d453d37b](https://user-images.githubusercontent.com/118952497/203689351-7f0caf9b-a983-495c-b06c-6759bb3870fa.jpeg)

**Comment by aitor-martinez-seras** [comment]
How did you manage to do it?
