### ISSUE TITLE
Issue with evaluation script

### ISSUE THREAD

**Issue by jadevaibhav** [deeplearning-wisc/stud#16]
Hi,

Thanks for the awesome work! I am trying to run the evaluation on BDD100k and COCO as per the readme.md. I am getting an issue in the src/data/builtin.py. I also tried to run datasets/domain_splits_bdd100k.py, it does not create the required files "bdd100k_mot_domain_splits_train.json"," bdd100k_mot_domain_splits_val.json". 
I tried to run an evaluation on the coco dataset by removing this dependency, with the given STUD-ResNet model.  It gives error 
```
raise KeyError(
KeyError: "No object named 'SSRCNN' found in 'META_ARCH' registry!")
```

This is my system configuration (as given by detectron2). Can you please guide me on how to get these issues resolved? Thanks!
:----------------------  --------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
numpy                   1.24.3
detectron2              0.6 @/home/vaibhav/Desktop/detectron2/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.2
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu102 @/home/vaibhav/Desktop/detectron2/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce RTX 2080 SUPER (arch=7.5)
Driver version          470.182.03
CUDA_HOME               /usr/local/cuda
Pillow                  9.5.0
torchvision             0.10.0+cu102 @/home/vaibhav/Desktop/detectron2/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20221221
iopath                  0.1.9
cv2                     Not found
----------------------  --------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by d12306** [comment]
hi, @jadevaibhav , I did not reproduce the error. Can you provide more context?

Such as the data sets. and whether you modify anything in the code base?
