### ISSUE TITLE
File path issue

### ISSUE THREAD

**Issue by lzylzylzy123456** [deeplearning-wisc/stud#20]
I tried to run the training process using the bdd100k dataset, but I couldn't get it to work. The code throws an error in builtin.py. Is "/nobackup-slow/dataset/my_xfdu/video/bdd/" a folder you define yourselves? How should I organize the data inside that folder? And how can I obtain bdd100k_mot_domain_splits_val.json and bdd100k_mot_domain_splits_train.json? I noticed many file paths like this in the code, and it seems that they all need to be modified? This doesn't seem to be clearly explained in your readme. How should I proceed?

**Comment by d12306** [comment]
Hi, @lzylzylzy123456 , thanks for your interest in the paper.

please replace the /nobackup-slow/dataset/my_xfdu/video/bdd/ with the ./datasets as specified in the readme file

For  bdd100k_mot_domain_splits_val.json and bdd100k_mot_domain_splits_train.json, please execute the following in the readme:
 ![image](https://github.com/deeplearning-wisc/stud/assets/42554178/350b6028-f62b-4701-bcdd-71762878bc06)
