### ISSUE TITLE
some problem with the builtin file

### ISSUE THREAD

**Issue by captain0305** [deeplearning-wisc/stud#3]
Hi! This work is quite amazing. And I have some problems with the file builtin.
I don't understand why there's a domain_path. And the file "bdd100k_mot_domain_splits_train.json" is different from the file convert "bdd100k/labels/track/bdd100k_mot_train_coco.json" or not? 

How could I generate the file under the domain_path?

` 

    _PREDEFINED_SPLITS_BDDT = {
        "bdd_tracking_2k": {
            "bdd_tracking_2k_train": (
                "bdd100k/images/track/train",
                "bdd100k/labels/track/bdd100k_mot_train_coco.json",
            ),
            "bdd_tracking_2k_val": (
                "bdd100k/images/track/val",
                "bdd100k/labels/track/bdd100k_mot_val_coco.json",
            ),
        },
    }

    # Register data for different domains as well as different sequence.
    domain_path = "bdd100k/labels/box_track_20/domain_splits/"

    train_splits = load_json(
        osp.join("/nobackup-slow/dataset/my_xfdu/video/bdd/", domain_path, "bdd100k_mot_domain_splits_train.json")
    )
    val_splits = load_json(
        osp.join("/nobackup-slow/dataset/my_xfdu/video/bdd/", domain_path, "bdd100k_mot_domain_splits_val.json")
    )
`

**Comment by captain0305** [comment]
I've solved this issue by using this [file](https://github.com/deeplearning-wisc/stud/blob/main/datasets/domain_splits_bdd100k.py)

**Comment by yeyang1021** [comment]
> I've solved this issue by using this [file](https://github.com/deeplearning-wisc/stud/blob/main/datasets/domain_splits_bdd100k.py)
Can you provide the specific process ?

**Comment by jadevaibhav** [comment]
@yeyang1021 Can you please explain how you are able to resolve this issue? Also,  @d12306 can you please provide the exact detectron2 library version you used? I am getting errors loading the SSRCN model (from stud_resnet_ood_coco.yaml). Thanks!
