### ISSUE TITLE
About the ood results

### ISSUE THREAD

**Issue by HopeFinder** [deeplearning-wisc/stud#6]
I have trained this model by STUD on ResNet (BDD as ID data) and follow your process. When I evalutate with the ood Dataset and visualize it by the cfg option '--visualize', the result pictures don't contain any "ood" labels. Could you tell me why? Thanks a lot.

**Comment by d12306** [comment]
hi @HopeFinder , please follow this issue https://github.com/deeplearning-wisc/stud/issues/5 and change the threshold and then visualize the results.

**Comment by HopeFinder** [comment]
> hi @HopeFinder , please follow this issue #5 and change the threshold and then visualize the results.

Hello! I have followed your reply in issue #5 and uncomment that two line in src/engine/myvisualizer.py. However this problem is still not solved. It looks like that there are not any instances detected as ood instances.

**Comment by d12306** [comment]
Hi, @HopeFinder , do you happen to change the threshold as what is discussed in issue 5?

**Comment by HopeFinder** [comment]
> Hi, @HopeFinder , do you happen to change the threshold as what is discussed in issue 5?

Hi, @d12306 , this problem has been solved by issue 4.Thank you all the same.
