### ISSUE TITLE
Some problem about your paper and code

### ISSUE THREAD

**Issue by HopeFinder** [deeplearning-wisc/stud#8]
Hello ! Your work for ood detection is wonderful ! But I notice that you don't mention how you get a ood counter-part of an id object in your paper. Could you please tell me how you distill an ood object in your code? Thanks !

**Comment by d12306** [comment]
hi, @HopeFinder , thanks for your interest in our work!

please see in section 3.1 of the main paper to get a sense of the method.
for code, please see https://github.com/deeplearning-wisc/stud/blob/main/src/modeling/self_supervised/cycle_energy_direct_add_all.py for details.

**Comment by HopeFinder** [comment]
> hi, @HopeFinder , thanks for your interest in our work!
> 
> please see in section 3.1 of the main paper to get a sense of the method. for code, please see https://github.com/deeplearning-wisc/stud/blob/main/src/modeling/self_supervised/cycle_energy_direct_add_all.py for details.

By reading your paper and code carefully, I know the answer. Thank you !
