### ISSUE TITLE
Confusing about t_0.

### ISSUE THREAD

**Issue by jinweiisgreat** [deeplearning-wisc/stud#9]
Thank you for your nice paper!
I have a question about the key frame :
- How to deal with $t_0$?
- Is there only one $t_0$ for each video?

**Comment by d12306** [comment]
hi, @jinweiisgreat , thanks for the interest in our work!

For frame t0, it is randomly selected from the frames in one video. we deal with t0 in the same way as in the other frames, i.e., letting it going through the object detection networks. The only different thing from the reference frames is that we force the energy scores for the objects that are in frame t0 to be higher.
